name: sachet
description: "An app designed for Xiangtan University students, offering easy-to-use course schedules, convenient free-classrooms search, clear exam information, and other features."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.7.2+12

homepage: https://github.com/wyvern1723/sachet
repository: https://github.com/wyvern1723/sachet

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # ðŸ‘‡ è¯·ç¡®ä¿ä¸‹é¢è¿™å‡ è¡Œçš„ç¼©è¿›å’Œä¸Šé¢çš„ flutter å¯¹é½
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^15.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # æ–‡ä»¶
  shared_preferences: ^2.3.5      # å­˜å‚¨ä¸é‡è¦çš„æ•°æ®(è®¾ç½®ç­‰)
  path_provider: ^2.1.5           # èŽ·å–æ–‡ä»¶ç³»ç»Ÿè·¯å¾„(Android/dataã€ä¸‹è½½è·¯å¾„â€¦â€¦)
  file_picker: ^8.1.7             # è°ƒèµ·ç³»ç»Ÿæ–‡ä»¶é€‰æ‹©å™¨
  flutter_secure_storage: ^9.2.4  # å®‰å…¨å‚¨å­˜ç”¨æˆ·æ•æ„Ÿä¿¡æ¯
  path: ^1.9.0                    # å…³äºŽæ–‡ä»¶è·¯å¾„çš„æ“ä½œï¼Œç›®å‰ç”¨äºŽä»Žæ–‡ä»¶è·¯å¾„æå–æ–‡ä»¶å

  # çŠ¶æ€ç®¡ç†
  provider: ^6.1.2 

  # ç½‘ç»œ
  http: ^1.2.2                    # Flutter å®˜æ–¹çš„ http åŒ…
  html: ^0.15.5
  dio: ^5.7.0                     # Dioï¼Œflutter ä¸­å¸¸ç”¨çš„ç½‘ç»œåŒ…
  flutter_inappwebview: ^6.1.5    # åº”ç”¨å†…æ˜¾ç¤º webview, ç”¨äºŽæ‰‹åŠ¨ç™»å½•

  # éªŒè¯ç å›¾ç‰‡è‡ªåŠ¨è¯†åˆ«(TensorFlow)
  tflite_flutter: ^0.11.0         # TensorFlow Lite(TFliteã€LiteRT) åº“
  image: ^4.1.0                   # å¯¹éªŒè¯ç å›¾ç‰‡è¿›è¡Œé¢„å…ˆå¤„ç†ï¼ˆç°åº¦åŒ–ã€äºŒå€¼åŒ–ï¼‰

  # è¾…åŠ©ç”Ÿæˆé¡¹ç›®æ–‡ä»¶çš„ packageï¼Œåº”ç”¨ä»£ç ä¸­æ²¡æœ‰ä¾èµ–å®ƒä»¬(ç”ŸæˆåŽåˆ é™¤ä»¥ä¸‹ä¸¤è¡Œæ— å½±å“)
  flutter_native_splash: ^2.4.4   # ç”Ÿæˆ splash screen (åº”ç”¨å¯åŠ¨æ—¶çš„ç•Œé¢)
  flutter_launcher_icons: ^0.14.2 # ç”Ÿæˆåº”ç”¨å›¾æ ‡

  # å…¶ä»–
  url_launcher: ^6.3.1            # (è°ƒèµ·æµè§ˆå™¨)æ‰“å¼€é“¾æŽ¥
  flutter_gbk2utf8: ^1.0.1        # è§£ç  GBK
  flutter_colorpicker: ^1.1.0     # é¢œè‰²é€‰æ‹©å™¨
  package_info_plus: ^8.1.2       # ç”¨äºŽèŽ·å–åº”ç”¨å½“å‰ç‰ˆæœ¬ä¿¡æ¯
  flutter_markdown: ^0.7.7        # ç”¨äºŽæ¸²æŸ“æ›´æ–°å†…å®¹çš„ Markdown
  dynamic_color: 1.7.0            # åŠ¨æ€å–è‰² [åŠ¨æ€é…è‰²](https://developer.android.com/develop/ui/views/theming/dynamic-colors?hl=zh-cn)
  pointycastle: ^4.0.0            # RSA åŠ å¯†ï¼Œç”¨äºŽæ­£æ–¹æ•™åŠ¡ç³»ç»Ÿç™»å½•æ—¶å¯¹ç”¨æˆ·å¯†ç çš„åŠ å¯†
  
  # æœ¬åœ°é€šçŸ¥
  flutter_local_notifications: ^19.4.2  # æœ¬åœ°é€šçŸ¥,ç”¨äºŽå‘é€è¯¾ç¨‹é€šçŸ¥(ä¸Šè¯¾æé†’)
  app_settings: ^6.1.1                  # ç”¨äºŽæ‰“å¼€ç³»ç»Ÿè®¾ç½®ä¸­çš„åº”ç”¨è®¾ç½®é¡µé¢
  timezone: ^0.10.1                     # flutter_local_notifications ç”¨åˆ°çš„
  disable_battery_optimization: ^1.1.2  # æ‰“å¼€è‡ªå¯åŠ¨/ç”µæ± ä¼˜åŒ–è®¾ç½® (Android)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# app icon (åº”ç”¨å›¾æ ‡)
# ç”Ÿæˆæœ‰å…³åº”ç”¨å›¾æ ‡çš„æ–‡ä»¶
# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon-fg.png"
  adaptive_icon_background: "assets/icon/icon-bg.png"
  adaptive_icon_monochrome: "assets/icon/icon-monochrome.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 256 # min:48, max:256, default: 48

# splash screen (åº”ç”¨å¯åŠ¨é¡µé¢)
# ç”Ÿæˆæœ‰å…³ splash screen çš„æ–‡ä»¶
# dart run flutter_native_splash:create
flutter_native_splash:
  image: assets/icon/icon-fg_1152x1152.png
  color: "#a5d6a7"
  color_dark: "#000000"
  fullscreen: true # éœ€è¦è®¾ä¸º trueï¼Œå¦åˆ™ä¼šæ˜¾ç¤ºç³»ç»Ÿçš„çŠ¶æ€æ 
  android_12:
    color: "#a5d6a7"
    color_dark: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/json/
    - assets/json/ClassSessionSummerRoutine.json  # å¤ä»¤æ—¶ä¸Šè¯¾æ—¶é—´
    - assets/json/ClassSessionWinterRoutine.json  # å†¬ä»¤æ—¶ä¸Šè¯¾æ—¶é—´
    - assets/models/captcha_model.tflite          # è‡ªåŠ¨è¯†åˆ«å›¾ç‰‡éªŒè¯ç çš„ tflite æ¨¡åž‹(ä½¿ç”¨ TensorFlow v2.15.0 è®­ç»ƒç”Ÿæˆ)
